connector_image: airbyte/source-amazon-seller-partner:dev
tests:
  spec:
    - spec_path: "source_amazon_seller_partner/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
      timeout_seconds: 60
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
      timeout_seconds: 60
  discovery:
    - config_path: "secrets/config.json"
# TODO: uncomment when any stream is filled with data. Records streams return different values each time
#  basic_read:
#    - config_path: "secrets/config.json"
#      configured_catalog_path: "integration_tests/configured_catalog_no_empty_streams.json"
#      empty_streams: []
# TODO: uncomment when Orders (or any other incremental) stream is filled with data
#  incremental:
#   - config_path: "secrets/config.json"
#     configured_catalog_path: "integration_tests/configured_catalog.json"
#     future_state_path: "integration_tests/future_state.json"
#     cursor_paths:
#       Orders: ["LastUpdateDate"]
#  full_refresh:
#   - config_path: "secrets/config.json"
#     configured_catalog_path: "integration_tests/configured_catalog.json"
